version: '3'
services:
    php:
        image: php:7.0-cli
        volumes:
          - ./:/redsms
        working_dir: '/redsms'
    php5:
        image: php:5.6-cli
        volumes:
          - ./:/redsms
        working_dir: '/redsms'